Class {
	#name : #LcsReadOnlyUnitOfWork,
	#superclass : #LcsUnitOfWork,
	#category : #'Lcs-UnitOfWOrk'
}

{ #category : #api }
LcsReadOnlyUnitOfWork >> addObject: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> applyChanges [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> changedSlot: aSlotName valueTo: anObject in: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> deleteObject: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> setValueTo: anObject in: aDomainObject forSlot: aSlotDefiniton [ 
	"do nothing"
]
